/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cryptochat.gui;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.nio.Buffer;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author raka
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private static final String putanjaKorisnici = "/korisnici";
    
    public Login() {
        initComponents();
        this.setTitle("Prijava");
        this.setLocationRelativeTo(null);
        neuspjesnoLogovanjeLabel.setText("");
        neuspjesnoLogovanjeLabel.setForeground(Color.red);
        //komentar test git
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lozinkaPasswordField = new javax.swing.JPasswordField();
        korisnickoImeTextField = new javax.swing.JTextField();
        korisnickoImeLabel = new javax.swing.JLabel();
        lozinkaLabel = new javax.swing.JLabel();
        prijavaNaSistemLabel = new javax.swing.JLabel();
        neuspjesnoLogovanjeLabel = new javax.swing.JLabel();
        prijavaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        korisnickoImeLabel.setText("Korisničko ime:");

        lozinkaLabel.setText("Lozinka: ");

        prijavaNaSistemLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prijavaNaSistemLabel.setText("PRIJAVA NA SISTEM");

        neuspjesnoLogovanjeLabel.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        neuspjesnoLogovanjeLabel.setText("jLabel1");

        prijavaButton.setText("Prijava");
        prijavaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prijavaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prijavaButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(korisnickoImeLabel)
                            .addComponent(lozinkaLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(korisnickoImeTextField)
                            .addComponent(lozinkaPasswordField)
                            .addComponent(neuspjesnoLogovanjeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(prijavaNaSistemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(prijavaNaSistemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(korisnickoImeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(korisnickoImeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lozinkaLabel)
                    .addComponent(lozinkaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(neuspjesnoLogovanjeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(prijavaButton)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prijavaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prijavaButtonActionPerformed
        String pass = new String(lozinkaPasswordField.getPassword());
        String korisnickoIme = korisnickoImeTextField.getText();
        if ("".equals(korisnickoImeTextField.getText()) || "".equals(pass)) {
            neuspjesnoLogovanjeLabel.setText("Korisničko ime / Lozinka");
        } else {
            BufferedReader reader = null;
            try {
                neuspjesnoLogovanjeLabel.setText("");
                reader = new BufferedReader(new FileReader("../korisnici.txt"));
                String line = null;
                while((line = reader.readLine()) != null){
                    String [] procitano = line.split("#");
                    if (procitano[0].equals(korisnickoIme) && procitano[1].equals(pass)) {
                        //ucitati novu formu
                        this.setVisible(false);
                        new Pocetna(korisnickoIme).setVisible(true);
                    } else {
                        neuspjesnoLogovanjeLabel.setText("Pogrešno korisničko ime/lozinka");
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    reader.close();
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
    }//GEN-LAST:event_prijavaButtonActionPerformed

    /**
     * 
     * -----
     * @param args the command line arguments
     * 
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel korisnickoImeLabel;
    private javax.swing.JTextField korisnickoImeTextField;
    private javax.swing.JLabel lozinkaLabel;
    private javax.swing.JPasswordField lozinkaPasswordField;
    private javax.swing.JLabel neuspjesnoLogovanjeLabel;
    private javax.swing.JButton prijavaButton;
    private javax.swing.JLabel prijavaNaSistemLabel;
    // End of variables declaration//GEN-END:variables
}
